const problems = [
    { number: 1, title: "Two Sum", path: "1-50/1/index", level: "Easy", runtime: "4ms", beats: "53.48%" },
    { number: 2, title: "Add Two Numbers", path: "1-50/2/index", level: "Medium", runtime: "20ms", beats: "5%" },
    { number: 3, title: "Longest Substring Without Repeating Characters", path: "1-50/3/index", level: "Medium", runtime: "79ms", beats: "13%" },
    { number: 4, title: "Median of Two Sorted Arrays", path: "1-50/4/index", level: "Hard", runtime: "87ms", beats: "5%" },
    { number: 5, title: "Longest Palindromic Substring", path: "1-50/5/index", level: "Medium", runtime: "72ms", beats: "26%" },
    { number: 6, title: "Zigzag Conversion", path: "1-50/6/index", level: "Medium", runtime: "86ms", beats: "11%" },
    { number: 7, title: "Reverse Integer", path: "1-50/7/index", level: "Medium", runtime: "40ms", beats: "6%" },
    { number: 8, title: "String to Integer (atoi)", path: "1-50/8/index", level: "Medium", runtime: "4ms", beats: "17%" },
    { number: 9, title: "Palindrome Number", path: "1-50/9/index", level: "Easy", runtime: "3ms", beats: "97%" },
    { number: 11, title: "Container With Most Water", path: "1-50/11/index", level: "Medium", runtime: "2ms", beats: "79%" },
    { number: 12, title: "Integer to Roman", path: "1-50/12/index", level: "Medium", runtime: "152ms", beats: "5%" },
    { number: 13, title: "Roman to Integer", path: "1-50/13/index", level: "Easy", runtime: "", beats: "" },
    { number: 14, title: "Longest Common Prefix", path: "1-50/14/index", level: "Easy", runtime: "", beats: "" },
    { number: 15, title: "3Sum", path: "1-50/15/index", level: "Medium", runtime: "", beats: "" },
    { number: 16, title: "3Sum Closest", path: "1-50/16/index", level: "Medium", runtime: "", beats: "" },
    { number: 17, title: "Letter Combinations of a Phone Number", path: "1-50/17/index", level: "Medium", runtime: "", beats: "" },
    { number: 18, title: "4Sum", path: "1-50/18/index", level: "Medium", runtime: "", beats: "" },
    { number: 19, title: "Remove Nth Node From Ed of List", path: "1-50/19/index", level: "Medium", runtime: "", beats: "" },
    { number: 20, title: "Valid Parentheses", path: "1-50/20/index", level: "Easy", runtime: "", beats: "" },
    { number: 21, title: "Merge Two Sorted Lists", path: "1-50/21/index", level: "Easy", runtime: "", beats: "" },
    { number: 22, title: "Generate Parentheses", path: "1-50/22/index", level: "Medium", runtime: "", beats: "" },
    { number: 23, title: "Merge k Sorted Lists", path: "1-50/23/index", level: "Hard", runtime: "", beats: "" },
    { number: 24, title: "Swap Nodes in Pairs", path: "1-50/24/index", level: "Medium", runtime: "", beats: "" },
    { number: 26, title: "Remove Duplicates from Sorted Array", path: "1-50/26/index", level: "Easy", runtime: "", beats: "" },
    { number: 27, title: "Remove Element", path: "1-50/27/index", level: "Easy", runtime: "", beats: "" },
    { number: 28, title: "Find the Index of the First Occurence in a String", path: "1-50/28/index", level: "Easy", runtime: "", beats: "" },
    { number: 29, title: "Divide Two Integer", path: "1-50/29/index", level: "Medium", runtime: "", beats: "" },
    { number: 31, title: "Next Permutation", path: "1-50/31/index", level: "Medium", runtime: "", beats: "" },
    { number: 33, title: "Search in Rotated Sorted Array", path: "1-50/33/index", level: "Medium", runtime: "", beats: "" },
    { number: 34, title: "Find First and Last Position of Element in Sorted Array", path: "1-50/34/index", level: "Medium", runtime: "", beats: "" },
    { number: 35, title: "Search Insert Position", path: "1-50/35/index", level: "Easy", runtime: "", beats: "" },
    { number: 36, title: "Valid Sudoku", path: "1-50/36/index", level: "Medium", runtime: "", beats: "" },
    { number: 38, title: "Count and Say", path: "1-50/38/index", level: "Medium", runtime: "", beats: "" },
    { number: 39, title: "Combination Sum", path: "1-50/39/index", level: "Medium", runtime: "", beats: "" },
    { number: 43, title: "Mutiply Strings", path: "1-50/43/index", level: "Medium", runtime: "", beats: "" },
    { number: 45, title: "Jump Game II", path: "1-50/45/index", level: "Medium", runtime: "", beats: "" },
    { number: 46, title: "Permutations", path: "1-50/46/index", level: "Medium", runtime: "", beats: "" },
    { number: 49, title: "Group Anagram", path: "1-50/49/index", level: "Medium", runtime: "", beats: "" },
    { number: 53, title: "Maximum Subarray", path: "51-100/53/index", level: "Medium", runtime: "", beats: "" },
    { number: 54, title: "Spiral Matrix", path: "51-100/54/index", level: "Medium", runtime: "", beats: "" },
    { number: 55, title: "Jump Game", path: "51-100/55/index", level: "Medium", runtime: "", beats: "" },
    { number: 57, title: "Insert Interval", path: "51-100/57/index", level: "Medium", runtime: "", beats: "" },
    { number: 58, title: "Length of Last Word", path: "51-100/58/index", level: "Easy", runtime: "", beats: "" },
    { number: 59, title: "Spiral Matrix II", path: "51-100/59/index", level: "Medium", runtime: "", beats: "" },
    { number: 62, title: "Unique Paths", path: "51-100/62/index", level: "Medium", runtime: "", beats: "" },
    { number: 63, title: "Unique Paths II", path: "51-100/63/index", level: "Medium", runtime: "", beats: "" },
    { number: 64, title: "Minimum Path Sum", path: "51-100/64/index", level: "Medium", runtime: "", beats: "" },
    { number: 66, title: "Plus One", path: "51-100/66/index", level: "Easy", runtime: "", beats: "" },
    { number: 67, title: "Add Binary", path: "51-100/67/index", level: "Easy", runtime: "", beats: "" },
    { number: 70, title: "Climbing Stairs", path: "51-100/70/index", level: "Easy", runtime: "", beats: "" },
    { number: 71, title: "Simplify Path", path: "51-100/71/index", level: "Medium", runtime: "", beats: "" },
    { number: 73, title: "Set Matrix Zeroes", path: "51-100/73/index", level: "Medium", runtime: "", beats: "" },
    { number: 74, title: "Search a 2D Matrix", path: "51-100/74/index", level: "Medium", runtime: "", beats: "" },
    { number: 75, title: "Sort Colors", path: "51-100/75/index", level: "Medium", runtime: "", beats: "" },
    { number: 78, title: "Subsets", path: "51-100/78/index", level: "Medium", runtime: "", beats: "" },
    { number: 86, title: "Partition List", path: "51-100/86/index", level: "Medium", runtime: "", beats: "" },
    { number: 88, title: "Merge Sorted Array", path: "51-100/88/index", level: "Easy", runtime: "", beats: "" },
    { number: 91, title: "Decode Ways", path: "51-100/91/index", level: "Medium", runtime: "", beats: "" },
    { number: 92, title: "Reverse Linked List II", path: "51-100/92/index", level: "Medium", runtime: "", beats: "" },
    { number: 93, title: "Restore IP Addresses", path: "51-100/93/index", level: "Medium", runtime: "", beats: "" },
    { number: 94, title: "Binary Tree Inorder Traversal", path: "51-100/94/index", level: "Easy", runtime: "", beats: "" },
    { number: 95, title: "Unique Binary Search Trees II", path: "51-100/95/index", level: "Medium", runtime: "", beats: "" },
    { number: 100, title: "Same Tree", path: "51-100/100/index", level: "Easy", runtime: "", beats: "" },
    { number: 101, title: "Symmetric Tree", path: "101-150/101/index", level: "Easy", runtime: "", beats: "" },
    { number: 102, title: "Binary Tree Level Order Traversal", path: "101-150/102/index", level: "Medium", runtime: "", beats: "" },
    { number: 103, title: "Binary Tree Zigzag Level Order Traversal", path: "101-150/103/index", level: "Medium", runtime: "", beats: "" },
    { number: 104, title: "Maximum Depth of Binary Tree", path: "101-150/104/index", level: "Easy", runtime: "", beats: "" },
    { number: 108, title: "Convert Sorted Array to Binary Search Tree", path: "101-150/108/index", level: "Easy", runtime: "", beats: "" },
    { number: 109, title: "Convert Sorted List to Binary Search Tree", path: "101-150/109/index", level: "Medium", runtime: "", beats: "" },
    { number: 111, title: "Minimum Depth of Binary Tree", path: "101-150/111/index", level: "Easy", runtime: "", beats: "" },
    { number: 116, title: "Populating Next Right Pointers in Each Node", path: "101-150/116/index", level: "Medium", runtime: "", beats: "" },
    { number: 118, title: "Pascal's Triangle", path: "101-150/118/index", level: "Easy", runtime: "", beats: "" },
    { number: 119, title: "Pascal's Triangle II", path: "101-150/119/index", level: "Easy", runtime: "", beats: "" },
    { number: 120, title: "Triangle", path: "101-150/120/index", level: "Medium", runtime: "", beats: "" },
    { number: 121, title: "Best Time to Buy and Sell Stock", path: "101-150/121/index", level: "Easy", runtime: "", beats: "" },
    { number: 122, title: "Best Time to Buy and Sell Stock II", path: "101-150/122/index", level: "Medium", runtime: "", beats: "" },
    { number: 124, title: "Binary Tree Maximum Path Sum", path: "101-150/124/index", level: "Hard", runtime: "", beats: "" },
    { number: 125, title: "Valid Palindrome", path: "101-150/125/index", level: "Easy", runtime: "", beats: "" },
    { number: 129, title: "Sum Root to Leaf Numbers", path: "101-150/129/index", level: "Medium", runtime: "", beats: "" },
    { number: 131, title: "Palindrome Partitioning", path: "101-150/131/index", level: "Medium", runtime: "", beats: "" },
    { number: 133, title: "Clone Graph", path: "101-150/133/index", level: "Medium", runtime: "", beats: "" },
    { number: 135, title: "Candy", path: "101-150/135/index", level: "Hard", runtime: "", beats: "" },
    { number: 136, title: "Single Number", path: "101-150/136/index", level: "Easy", runtime: "", beats: "" },
    { number: 138, title: "Copy List with Random Pointer", path: "101-150/138/index", level: "Medium", runtime: "", beats: "" },
    { number: 141, title: "Linked List Cycle", path: "101-150/141/index", level: "Easy", runtime: "", beats: "" },
    { number: 142, title: "Linked List Cycle II", path: "101-150/142/index", level: "Medium", runtime: "", beats: "" },
    { number: 143, title: "Reorder List", path: "101-150/143/index", level: "Medium", runtime: "", beats: "" },
    { number: 144, title: "Binary Tree Preorder Traversal", path: "101-150/144/index", level: "Easy", runtime: "", beats: "" },
    { number: 474, title: "Ones and Zeroes", path: "451-500/474/index", level: "Medium", runtime: "", beats: "" },
    { number: 717, title: "1-bit and 2-bit Characters", path: "701-750/717/index", level: "Easy", runtime: "", beats: "" },
    { number: 757, title: "Set Intersection Size At Least Two", path: "751-800/757/index", level: "Hard", runtime: "", beats: "" },
    { number: 961, title: "N-Repeated Element in Size 2N Array", path: "951-1000/961/index", level: "Easy", runtime: "0ms", beats: "100%" },
    { number: 1015, title: "Smallest Integer Divisible by K", path: "1001-1050/1015/index", level: "Medium", runtime: "", beats: "" },
    { number: 1018, title: "Binary Prefix Divisibly By 5", path: "1001-1050/1018/index", level: "Medium", runtime: "", beats: "" },
    { number: 1262, title: "Greatest Sum Divisible by Three", path: "1251-1300/1262/index", level: "Medium", runtime: "", beats: "" },
    { number: 1351, title: "Count Negative Numbers in a Sorted Matrix", path: "1301-1350/1351/index", level: "Easy", runtime: "0ms", beats: "100%" },
    { number: 1437, title: "Check If All 1's Are at Least Length K Places Away", path: "1401-1450/1437/index", level: "Easy", runtime: "", beats: "" },
    { number: 1526, title: "Minimum Number of Increments on Subarrays to Form a Target Array", path: "1501-1550/1526/index", level: "Hard", runtime: "", beats: "" },
    { number: 1925, title: "Count Square Sum Triples", path: "1901-1950/1925/index", level: "Easy", runtime: "", beats: "" },
    { number: 1930, title: "Unique Length-3 Palindromi Subsequences", path: "1901-1950/1930/index", level: "Medium", runtime: "", beats: "" },
    { number: 2011, title: "Final Value of Variable After Performing Operations", path: "2001-2050/2011/index", level: "Easy", runtime: "", beats: "" },
    { number: 2110, title: "Number of Smooth Descent Periods of a Stock", path: "2101-2150/2110/index", level: "Medium", runtime: "", beats: "" },
    { number: 2125, title: "Number of Laser Beams in a Bank", path: "2101-2150/2125/index", level: "Medium", runtime: "", beats: "" },
    { number: 2154, title: "Keep Multiplying Found Values by Two", path: "2151-2200/2154/index", level: "Easy", runtime: "", beats: "" },
    { number: 3190, title: "Find Minimum Operations to Make All Elements Divisible by Three", path: "3151-3200/3190/index", level: "Easy", runtime: "", beats: "" },
    { number: 3370, title: "Smallest Number With All Set Bits", path: "3351-3400/3370/index", level: "Easy", runtime: "", beats: "" },
    { number: 3397, title: "Maximum Number of Distinct Elements After Operations", path: "3351-3400/3397/index", level: "Medium", runtime: "", beats: "" },
    { number: 3432, title: "Count Partitions with Even Sum Difference", path: "3401-3450/3432/index", level: "Easy", runtime: "", beats: "" },
    { number: 3433, title: "Count Mentions Per User", path: "3401-3450/3433/index", level: "Medium", runtime: "", beats: "" },
    { number: 3461, title: "Check If Digits Are Equal in String After Operations I", path: "3451-3500/3461/index", level: "Easy", runtime: "", beats: "" },
    { number: 3583, title: "Count Special Triplets", path: "3551-3600/3583/index", level: "Medium", runtime: "", beats: "" },
    { number: 3606, title: "Coupon Code Validator", path: "3601-3650/3606/index", level: "Easy", runtime: "", beats: "" }
];
